### PR TITLE
Move changelog into its own file

### PR DESCRIPTION
**Pull request by mthjones**
The changelog keeps growing and pushing the code further and further down (not to mention the documentation). This PR moves it out of `lib.rs` and into its own `CHANGELOG.md` file.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Would it be better to have a `changelog.rs` file? I'm not sure how idiomatic it was but I did somewhat like having the changelog visible in the generated online documentation.

**Comment by mthjones** [comment]
What about adding a link to the Changelog from the docs? Would allow it to be found easily without having it bloat the documentation unnecessarily.

**Comment by BenTheElder** [comment]
That sounds like a good solution.

**Comment by BenTheElder** [comment]
LGTM :+1:

**Pull request merged**
