### PR TITLE
Update copyright boilerplate and add AUTHORS.

### PR DESCRIPTION
**Pull request by BenTheElder**
Updates copyright information.
Something similar will need to be done for the new api crate.

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @mthjones

**Comment by BenTheElder** [comment]
Actually using the same boilerplate is incorrect, some of these files do NOT date back to 2014 nor do their contents.

**Comment by BenTheElder** [comment]
I think this should be correct now, squashing it next.

After this we'll need to do a similar fix for [slack-rs-api](https://github.com/slack-rs/slack-rs-api).

**Comment by mthjones** [comment]
Hmm...I've never bothered to attach license information to every file since IMO it just adds unnecessary cruft to the source. The entire repository is already licensed according to the LICENSE file. But I know some people have strong opinions on licensing and I really don't, so I won't argue that too much. :)

**Comment by BenTheElder** [comment]
The license on every file bit is cargo-culted from other projects, I don't
have a strong opinion on it but it seems pretty easy to copy-paste the
header and occasionally bump the year.

**Comment by BenTheElder** [comment]
We should probably update everything to match the docs here:
http://www.apache.org/dev/apply-license.html and here:
http://www.apache.org/licenses/LICENSE-2.0

(Also it turns out the license header is mentioned here:
http://www.apache.org/dev/apply-license.html#new and:
http://www.apache.org/licenses/LICENSE-2.0#apply)

**Comment by BenTheElder** [comment]
A `NOTICE` file is mentioned but seems optional and I do not think that we need one.

I admit that the licensing was applied hastily originally and that I have not kept on top of it, but hopefully we should be able to get that and the organization change straightened out.

Speaking of, as an aside another issue to look into will be crates.up publishing.

**Comment by mthjones** [comment]
Yeah. Well, that does say *should* include the header. ;) I'll look at carrying over the header here into the new repo's files.

Not to derail this, but about crates.io publishing, I think we could implement a travis task to publish on tagged commits.

**Comment by BenTheElder** [comment]
That sounds good. Let's set up an issue for Travis/publishing.

**Comment by mthjones** [comment]
LGTM :+1:

**Pull request merged**
