### PR TITLE
Use new slack_api crate

### PR DESCRIPTION
**Pull request by mthjones**
I've split the low level API in this repo out into a new crate called `slack_api` (retaining the git history): https://github.com/mthjones/slack-rs-api. I will transfer ownership of the git repo into the `slack-rs` org, but don't have permissions to currently.

I've found some drawbacks here:
* have to keep hyper versions in sync between the two libraries. We should anyways (bumping a version in a dependency should suggest bumping the lib's version as well), but it may be worth considering removing the methods from `RtmClient` that just call the API methods.
* the error module is slightly duplicated. I imagine this could be improved fairly easily though.
* need to implement Travis builds and docs hosting for the slack-rs-api crate still

### CODE REVIEW

**Comment by BenTheElder** [comment]
Permissions: Should be fixed now.

Hyper: We should probably remove the methods that just call API methods, breaking changes like this seem acceptable as we haven't hit 1.0 yet and don't really have active users, and the restructure especially seems worth it.

Error Module: Not sure what we should do about that.

Travis: Yes, that needs doing.

I will also transfers slack-rs to the slack-rs org in a moment, and once the restructure is finished we'll get an up to date crate published.

**Comment by mthjones** [comment]
Do you want me to remove the methods in this PR or should that wait until another one?

**Comment by BenTheElder** [comment]
I think that should probably be a seperate PR.

**Comment by BenTheElder** [comment]
LGTM

**Pull request merged**
