### PR TITLE
Add RtmClient::send_rich_message

### PR DESCRIPTION
**Pull request by asayers**
A convenience method for sending messages with attachments.

### CODE REVIEW

**Comment by BenTheElder** [comment]
@mthjones how does this interact with the codegen changes upstream? Will this be necessary?

**Comment by asayers** [comment]
On second thought, this is the wrong way to do this. I should make a patch for slack-api-schemas instead.

**Comment by mthjones** [comment]
I'm hesitant to add (more) methods to the `RtmClient` that just proxy to the web API. I think these methods are best left just in `slack_api` as either another library that needs to be pulled in or re-exported as an `api` module from this library.

Regarding the actual changes here -- there are going to be few breaking changes from the new release that would break this change as well.

I'd like to improve this use case (currently the method just takes an `Option<&str>` for attachments), but I don't think this is the right way to do so.

**Comment by dten** [comment]
Just thought I'd chime in. In my app I made a very rough message builder struct where you could assign at the bits you need before sending it. Also an attachment builder. Seemed nicer than the method with lots of `None`s

**Comment by mthjones** [comment]
Yep, I've done the same thing as well. It'd be nice if everyone didn't have
to reimplement that themselves though. :)

Regarding passing a bunch of Nones, that goes away in the next release.
Instead of passing each param, each method now takes a struct that derives
Default, so you can just toss a ..Default::default() in there to fill in
the fields you don't care about.

**Comment by dten** [comment]
Ah that'll be nice :) can't wait

**Pull request closed without merging**
