### PR TITLE
Send typing

### PR DESCRIPTION
**Pull request by vampolo**
Add cli capability to send typing indicator as described in https://api.slack.com/rtm

### CODE REVIEW

**Comment by BenTheElder** [comment]
Could you please document the send_typing method like the other methods (if only just a comment pointing to the rtm docs for the event). Also, perhaps we should name the get_channel* methods differently since this currently introduces a breaking change in an existing method.

**Comment by vampolo** [comment]
Did add some changes, including disambiguating the added function to resolve channel ids and make it not `pub`

**Comment by BenTheElder** [comment]
Thanks, LGTM

**Comment by BenTheElder** [comment]
Thanks!
I like the collapse and check idea, that also makes the change non-breaking.

**Pull request merged**
