### PR TITLE
Add an async message send API

### LINKED ISSUE #50: Allow async message sending
Right now the way the API is constructed, we can only send messages from the `slack::EventHandler` implementation; that is, when an event or ping is received. This is very limiting, since it means we cannot send messages based on events generated by something other than Slack, like another thread. Would it be possible to redesign the interface to remove this limitation?

### PR DESCRIPTION
**Pull request by jwilm**
The current interface only allows for sending messages synchronously in
response to some event. In the past, it was possible to get an
`mpsc::Sender<WsMessage`> to deliver messages asynchronously. This commit
restores that functionality with a slighly more ergonomic API.

The `RtmClient` has a new method

    pub fn channel(&self) -> Option<Sender>

which returns a `slack::Sender` if the `RtmClient` has been logged in
(creating the `slack::Sender` requires the `RtmClient`'s `mpsc::Sender` to
initialize itself).

`Sender` has a high and low level send API. The high level API

    pub fn send_message_chid(&self, channel_id: &str, text: &str)

will automatically increment the message id, build the JSON payload, and
send it to the event loop for delivery. The low level API is two parts

    pub fn get_msg_uid(&self) -> isize

for getting the next message id, and

    pub fn send(&self, raw: &str)

for sending a pre-built JSON payload.

Resolves #50.

### CODE REVIEW

**Comment by BenTheElder** [comment]
This looks good to me, thanks!

**Comment by BenTheElder** [comment]
I will try to get out a release soon, I'm finishing a final project right now over at: https://github.com/fenichelar/CS4731Capstone
Once that's done (tonight/tomorrow) I'll update the changelog and push a release.

**Comment by jwilm** [comment]
Awesome; thank you!

**Comment by BenTheElder** [comment]
Version`0.15.0` is now live on [crates.io](https://crates.io/crates/slack).

**Comment by jwilm** [comment]
Thanks for the update 😁

**Pull request merged**
